"use client";
import { useEffect, useState } from "react";
import type { Team } from "../data/league";
import { getSponsor } from "../data/sponsors";
type Payment={team_slug:string;tranche:number;amount:number;charged_at:string};
type SponsorRow={sponsor_slug:string;locked_at:string};
export function AdminPanel({teams}:{teams:Team[]}){
 const[choices,setChoices]=useState<Record<string,Record<string,unknown>>>({}),[payments,setPayments]=useState<Payment[]>([]),[sponsors,setSponsors]=useState<Record<string,SponsorRow|null>>({}),[working,setWorking]=useState(""),[message,setMessage]=useState("");
 function refresh(){fetch("/api/choices").then(r=>r.json()).then(data=>setChoices(Object.fromEntries((data.choices??[]).map((choice:Record<string,unknown>)=>[choice.team_slug,choice]))));fetch("/api/salaries").then(r=>r.json()).then(data=>setPayments(data.payments??[]));Promise.all(teams.map(async team=>{const data=await fetch(`/api/sponsors?team=${team.slug}`).then(r=>r.json());return[team.slug,data.sponsor??null]as const})).then(rows=>setSponsors(Object.fromEntries(rows)))}
 useEffect(refresh,[]);
 async function unlock(teamSlug:string){const response=await fetch("/api/admin/unlock",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug})});setMessage(response.ok?"Modifiche riaperte per il club.":"Sblocco non riuscito.");if(response.ok)refresh()}
 async function resetSponsor(teamSlug:string){const key=`${teamSlug}-sponsor`;setWorking(key);const response=await fetch("/api/admin/reset-sponsor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug})}),data=await response.json().catch(()=>({}));setWorking("");setMessage(response.ok?"Sponsor resettato: il club può sceglierne uno nuovo.":data.error??"Reset sponsor non riuscito.");if(response.ok)refresh()}
 async function charge(teamSlug:string,tranche:number){const key=`${teamSlug}-${tranche}`;setWorking(key);const response=await fetch("/api/salaries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug,tranche})}),data=await response.json().catch(()=>({}));setWorking("");setMessage(response.ok?`${tranche===1?"Prima":"Seconda"} tranche addebitata una sola volta.`:data.error??"Addebito non riuscito.");if(response.ok)refresh()}
 return <><section className="page-heading"><p className="eyebrow">Area amministratore</p><h1>Controllo lega</h1><p>Gestisci scelte societarie, sponsor e due tranche degli stipendi.</p></section>{message&&<p className="admin-message">{message}</p>}<section className="admin-grid">{teams.map(team=>{const choice=choices[team.slug],locked=Boolean(choice?.locked_at),clubSponsor=sponsors[team.slug],sponsorName=getSponsor(clubSponsor?.sponsor_slug)?.name,teamPayments=payments.filter(p=>p.team_slug===team.slug),paid=teamPayments.reduce((sum,p)=>sum+p.amount,0),installment=Math.ceil(team.spent*.03),balance=team.remaining-paid,sponsorKey=`${team.slug}-sponsor`;return <article className={`surface admin-club ${balance<0?"balance-negative":""}`} key={team.slug}><div><div><h2>{team.name}</h2><small>Saldo attuale: <b>{balance} cr</b>{balance<0&&<em>Mancano {Math.abs(balance)} crediti per tornare a 0</em>}</small></div><span className={`admin-state ${locked?"locked":"open"}`}>{locked?"Scelte bloccate":"Scelte modificabili"}</span></div><button className="secondary-button" disabled={!locked} onClick={()=>unlock(team.slug)}>{locked?"Riapri scelte":"Nessun blocco"}</button><div className="sponsor-admin"><p>Sponsor stagionale</p><b>{sponsorName??"Nessuno sponsor scelto"}</b><button className="secondary-button" disabled={!clubSponsor||working===sponsorKey} onClick={()=>resetSponsor(team.slug)}>{working===sponsorKey?"Reset…":clubSponsor?"Reset sponsor":"Nessuno sponsor da resettare"}</button></div><div className="salary-admin"><p>Stipendi · 3% per tranche</p>{[1,2].map(tranche=>{const payment=teamPayments.find(p=>p.tranche===tranche),key=`${team.slug}-${tranche}`;return <button key={tranche} disabled={Boolean(payment)||working===key} onClick={()=>charge(team.slug,tranche)}><span>{tranche===1?"Prima tranche":"Seconda tranche"}</span><b>{payment?`Pagata −${payment.amount} cr`:`Scala ${installment} cr`}</b><small>{payment?new Date(payment.charged_at).toLocaleString("it-IT"):"Disponibile una sola volta"}</small></button>})}</div></article>})}</section></>}
