"use client";
import { useEffect,useState } from "react";
import type { Team } from "../data/league";
type Payment={team_slug:string;tranche:number;amount:number;charged_at:string};
export function AdminPanel({teams}:{teams:Team[]}){
  const[choices,setChoices]=useState<Record<string,Record<string,unknown>>>({}),[payments,setPayments]=useState<Payment[]>([]),[working,setWorking]=useState(""),[message,setMessage]=useState("");
  function refresh(){fetch("/api/choices").then(r=>r.json()).then(data=>setChoices(Object.fromEntries((data.choices??[]).map((choice:Record<string,unknown>)=>[choice.team_slug,choice]))));fetch("/api/salaries").then(r=>r.json()).then(data=>setPayments(data.payments??[]))}
  useEffect(refresh,[]);
  async function unlock(teamSlug:string){const response=await fetch("/api/admin/unlock",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug})});setMessage(response.ok?"Modifiche riaperte per il club.":"Sblocco non riuscito.");if(response.ok)refresh()}
  async function charge(teamSlug:string,tranche:number){const key=`${teamSlug}-${tranche}`;setWorking(key);const response=await fetch("/api/salaries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug,tranche})}),data=await response.json().catch(()=>({}));setWorking("");setMessage(response.ok?`${tranche===1?"Prima":"Seconda"} tranche addebitata una sola volta.`:data.error??"Addebito non riuscito.");if(response.ok)refresh()}
  return <><section className="page-heading"><p className="eyebrow">Area amministratore</p><h1>Controllo lega</h1><p>Gestisci il blocco delle scelte e addebita le due tranche degli stipendi. Ogni pulsante può essere usato una sola volta per club.</p></section>{message&&<p className="admin-message">{message}</p>}<section className="admin-grid">{teams.map(team=>{const choice=choices[team.slug],locked=Boolean(choice?.locked_at),teamPayments=payments.filter(p=>p.team_slug===team.slug),paid=teamPayments.reduce((sum,p)=>sum+p.amount,0),installment=Math.ceil(team.spent*.03);return <article className="surface admin-club" key={team.slug}><div><div><h2>{team.name}</h2><small>Saldo attuale: <b>{Math.max(0,team.remaining-paid)} cr</b></small></div><span className={`admin-state ${locked?"locked":"open"}`}>{locked?"Scelte bloccate":"Scelte modificabili"}</span></div><button className="secondary-button" disabled={!locked} onClick={()=>unlock(team.slug)}>{locked?"Riapri scelte":"Nessun blocco"}</button><div className="salary-admin"><p>Stipendi · 3% per tranche</p>{[1,2].map(tranche=>{const payment=teamPayments.find(p=>p.tranche===tranche),key=`${team.slug}-${tranche}`;return <button key={tranche} disabled={Boolean(payment)||working===key} onClick={()=>charge(team.slug,tranche)}><span>{tranche===1?"Prima tranche":"Seconda tranche"}</span><b>{payment?`Pagata −${payment.amount} cr`:`Scala ${installment} cr`}</b><small>{payment?new Date(payment.charged_at).toLocaleString("it-IT"):"Disponibile una sola volta"}</small></button>})}</div></article>})}</section></>
}
