"use client";
import { useEffect,useState } from "react";
type Leader={teamSlug:string;teamName:string;wins:number;losses:number;draws:number;played:number;points:number};
type Lobby={myTeam:string;online:{teamSlug:string;teamName:string}[];pending:{id:string;challenger_team:string;mode:string}[];active?:{id:string}|null;leaderboard:Leader[]};
type Match={id:string;mode:string;status:string;currentRound:number;totalRounds:number;myTeam:string;challengerTeam:string;opponentTeam:string;myScore:number;opponentScore:number;winnerTeam:string|null;answered:boolean;question:{prompt:string;clues:string[];options:string[]}|null};
const modeName=(mode:string)=>mode==="guess"?"Indovina il calciatore":"Quiz Serie A";
export function ArenaClient(){
 const[lobby,setLobby]=useState<Lobby|null>(null),[match,setMatch]=useState<Match|null>(null),[selectedMode,setSelectedMode]=useState("guess"),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function api(body:Record<string,unknown>){const response=await fetch("/api/arena",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Operazione non riuscita");return data}
 async function refreshLobby(){const data=await fetch("/api/arena").then(r=>r.json());setLobby(data);if(data.active?.id)openMatch(data.active.id)}
 async function openMatch(id:string){const data=await fetch(`/api/arena?match=${id}`).then(r=>r.json());if(data.match)setMatch(data.match)}
 useEffect(()=>{api({action:"heartbeat"}).then(refreshLobby).catch(()=>{});const heartbeat=setInterval(()=>api({action:"heartbeat"}).catch(()=>{}),15000),poll=setInterval(()=>match?openMatch(match.id):refreshLobby(),2000);return()=>{clearInterval(heartbeat);clearInterval(poll)}},[match?.id]);
 async function challenge(opponentTeam:string){setBusy(opponentTeam);setMessage("");try{await api({action:"challenge",opponentTeam,mode:selectedMode});setMessage("Sfida inviata. Aspetta che l’avversario accetti.");await refreshLobby()}catch(error){setMessage(error instanceof Error?error.message:"Errore")}setBusy("")}
 async function accept(matchId:string){setBusy(matchId);try{await api({action:"accept",matchId});await openMatch(matchId)}catch(error){setMessage(error instanceof Error?error.message:"Errore")}setBusy("")}
 async function answer(answerIndex:number){if(!match)return;setBusy("answer");try{const data=await api({action:"answer",matchId:match.id,round:match.currentRound,answerIndex});setMessage(data.correct?"Risposta corretta: punto tuo!":"Risposta errata. Vediamo cosa combina l’avversario…");await openMatch(match.id)}catch(error){setMessage(error instanceof Error?error.message:"Errore")}setBusy("")}
 if(match)return <section className="arena-match surface"><div className="arena-score"><div><span>Tu</span><strong>{match.myScore}</strong></div><b>{modeName(match.mode)}<small>{match.status==="finished"?"Partita terminata":`Round ${Math.min(match.currentRound+1,match.totalRounds)}/${match.totalRounds}`}</small></b><div><span>Avversario</span><strong>{match.opponentScore}</strong></div></div>{match.status==="finished"?<div className="arena-result"><p className="eyebrow">Risultato finale</p><h2>{!match.winnerTeam?"Pareggio":match.winnerTeam===match.myTeam?"Hai vinto!":"Hai perso"}</h2><p>{match.winnerTeam===match.myTeam?"Tre punti in classifica. Modalità boss attivata.":!match.winnerTeam?"Un punto a testa, nessun ferito grave.":"Zero punti, ma la rivincita è già nell’aria."}</p><button className="save-button" onClick={()=>{setMatch(null);setMessage("");refreshLobby()}}>Torna alla BDC Arena</button></div>:match.question?<div className="arena-question"><p>{match.question.prompt}</p>{match.question.clues.length>0&&<div className="arena-clues">{match.question.clues.map(clue=><span key={clue}>{clue}</span>)}</div>}<div className="arena-options">{match.question.options.map((option,index)=><button disabled={match.answered||busy==="answer"} onClick={()=>answer(index)} key={`${option}-${index}`}>{option}</button>)}</div>{match.answered&&<small>Risposta inviata. Aspettiamo l’altro allenatore…</small>}</div>:<p>Preparazione del prossimo round…</p>}{message&&<p className="arena-message">{message}</p>}</section>;
 return <>{message&&<p className="arena-message">{message}</p>}<section className="arena-lobby-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Allenatori disponibili</p><h2>Sfida chi è online</h2></div><span className="status-dot">{lobby?.online.length??0} online</span></div><div className="arena-mode"><button className={selectedMode==="guess"?"selected":""} onClick={()=>setSelectedMode("guess")}><b>Indovina il calciatore</b><small>5 round · indizi e quattro risposte</small></button><button className={selectedMode==="quiz"?"selected":""} onClick={()=>setSelectedMode("quiz")}><b>Quiz Serie A</b><small>10 domande · club e ruoli Mantra</small></button></div><div className="online-list">{lobby?.online.length?lobby.online.map(opponent=><div key={opponent.teamSlug}><i/><b>{opponent.teamName}</b><button disabled={Boolean(busy)} onClick={()=>challenge(opponent.teamSlug)}>{busy===opponent.teamSlug?"Invio…":"Sfida"}</button></div>):<p>Nessun altro allenatore online. Convoca qualcuno nella chat del gruppo, senza pietà.</p>}</div>{lobby?.pending.length?<div className="incoming"><p className="eyebrow">Sfide ricevute</p>{lobby.pending.map(item=><div key={item.id}><span>{item.challenger_team}</span><b>{modeName(item.mode)}</b><button disabled={Boolean(busy)} onClick={()=>accept(item.id)}>{busy===item.id?"Ingresso…":"Accetta"}</button></div>)}</div>:null}</div><div className="surface arena-how"><p className="eyebrow">Come si gioca</p><h2>Duello in tempo reale</h2><ol><li>Scegli una modalità e sfida un allenatore online.</li><li>L’avversario accetta e la partita parte per entrambi.</li><li>Il primo che risponde correttamente prende il punto.</li><li>Vittoria 3 punti, pareggio 1, sconfitta 0.</li></ol></div></section><section className="surface arena-ranking"><div className="surface-title"><div><p className="eyebrow">Classifica completa</p><h2>BDC Arena</h2></div></div><div className="arena-table-wrap"><table><thead><tr><th>#</th><th>Club</th><th>G</th><th>V</th><th>P</th><th>S</th><th>Pt</th></tr></thead><tbody>{lobby?.leaderboard.map((row,index)=><tr className={row.teamSlug===lobby.myTeam?"mine":""} key={row.teamSlug}><td>{index+1}</td><td><b>{row.teamName}</b></td><td>{row.played}</td><td>{row.wins}</td><td>{row.draws}</td><td>{row.losses}</td><td><strong>{row.points}</strong></td></tr>)}</tbody></table></div></section></>;
}
