"use client";
import { useEffect, useMemo, useState } from "react";
import type { Team } from "../data/league";
import { formations } from "../data/league";

function eligible(playerRole:string,slot:string){const player=playerRole.split("/"),accepted=slot.split("/");return player.some(role=>accepted.includes(role));}

export function FormationBuilder({team}:{team:Team}){
  const [formationIndex,setFormationIndex]=useState(0),[lineup,setLineup]=useState<Record<string,string>>({}),[message,setMessage]=useState("");
  const formation=formations[formationIndex];
  useEffect(()=>{fetch(`/api/choices?team=${team.slug}`).then(r=>r.json()).then(data=>{if(data.choice){const idx=formations.findIndex(f=>f.name===data.choice.formation);if(idx>=0)setFormationIndex(idx);try{setLineup(JSON.parse(data.choice.lineup_json??"{}"));}catch{}}}).catch(()=>{});},[team.slug]);
  const used=useMemo(()=>new Set(Object.values(lineup)),[lineup]);
  function changeFormation(index:number){setFormationIndex(index);setLineup({});setMessage("");}
  function autoFill(){const next:Record<string,string>={},taken=new Set<string>();formation.slots.forEach((slot,index)=>{const player=team.roster.filter(p=>!taken.has(p.name)&&eligible(p.role,slot)).sort((a,b)=>b.cost-a.cost)[0];if(player){next[String(index)]=player.name;taken.add(player.name);}});setLineup(next);setMessage(Object.keys(next).length===11?"Formazione suggerita completata.":"Alcuni slot non hanno un ruolo compatibile in rosa.");}
  async function save(){if(Object.keys(lineup).length<11){setMessage("Completa tutti gli undici slot prima di salvare.");return;}const response=await fetch("/api/choices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"formation",teamSlug:team.slug,formation:formation.name,lineup})});setMessage(response.ok?"Formazione pubblicata: gli altri club possono visualizzare il modulo.":"Non sono riuscito a salvare la formazione.");}
  return <><section className="page-heading formation-heading"><div><p className="eyebrow">Simulatore Mantra</p><h1>Costruisci la formazione</h1><p>Vengono proposti soltanto i calciatori della tua rosa compatibili con lo slot selezionato.</p></div><div className="formation-controls"><label>Modulo<select value={formationIndex} onChange={e=>changeFormation(Number(e.target.value))}>{formations.map((f,i)=><option key={f.name} value={i}>{f.name}</option>)}</select></label><button className="secondary-button" onClick={autoFill}>Suggerisci undici</button></div></section><section className="formation-layout"><div className={`pitch formation-${formation.name.replaceAll("-","")}`}><div className="pitch-lines"/><div className="lineup-grid">{formation.slots.map((slot,index)=>{const current=lineup[String(index)]??"";return <label className={`player-slot ${current?"filled":""}`} key={`${formation.name}-${index}`}><span>{slot}</span><select value={current} onChange={e=>setLineup(prev=>({...prev,[String(index)]:e.target.value}))}><option value="">Seleziona</option>{team.roster.filter(p=>eligible(p.role,slot)&&(!used.has(p.name)||p.name===current)).map(p=><option key={p.name} value={p.name}>{p.name} · {p.role}</option>)}</select></label>})}</div></div><aside className="surface formation-side"><p className="eyebrow">Distinta</p><h2>{team.name}</h2><ol>{formation.slots.map((slot,index)=><li key={index}><span>{slot}</span><b>{lineup[String(index)]||"Slot vuoto"}</b></li>)}</ol><button className="save-button" onClick={save}>Salva formazione</button>{message&&<p className="form-message">{message}</p>}<small>La compatibilità è una simulazione regolamentare; il calcolo ufficiale resta quello di Leghe Fantacalcio.</small></aside></section></>
}
