"use client";
import { useEffect,useState } from "react";
import type { Team } from "../data/league";

type Avatar={skin:string;face:string;eyes:string;eyeColor:string;hair:string;hairColor:string;beard:string;beardColor:string;shirt:string};
type Kit={primary:string;secondary:string;accent:string;pattern:string;collar:string;shorts:string};
const defaultAvatar:Avatar={skin:"#d99b6c",face:"oval",eyes:"round",eyeColor:"#4b301e",hair:"short",hairColor:"#2a1a12",beard:"short",beardColor:"#2a1a12",shirt:"#0a3a4d"};
const defaultKit:Kit={primary:"#06384b",secondary:"#32b7be",accent:"#d7a62c",pattern:"stripes",collar:"v",shorts:"#082537"};
const Select=({label,value,onChange,items}:{label:string;value:string;onChange:(v:string)=>void;items:[string,string][]})=><label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{items.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label>;
const Color=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label>{label}<input type="color" value={value} onChange={e=>onChange(e.target.value)}/></label>;

export function IdentityStudio({team}:{team:Team}){
 const [avatar,setAvatar]=useState(defaultAvatar),[kit,setKit]=useState(defaultKit),[crest,setCrest]=useState<File|null>(null),[crestUrl,setCrestUrl]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch(`/api/identity?team=${team.slug}`).then(r=>r.json()).then(data=>{if(data.identity){try{setAvatar(JSON.parse(data.identity.avatar_json));setKit(JSON.parse(data.identity.kit_json));}catch{}if(data.identity.crest_key)setCrestUrl(`/api/identity/crest?team=${team.slug}&v=${Date.now()}`)}})},[team.slug]);
 function av<K extends keyof Avatar>(key:K,value:Avatar[K]){setAvatar(x=>({...x,[key]:value}));} function kt<K extends keyof Kit>(key:K,value:Kit[K]){setKit(x=>({...x,[key]:value}));}
 function chooseFile(file:File|null){setCrest(file);if(file)setCrestUrl(URL.createObjectURL(file));}
 async function save(){setBusy(true);setMessage("");const data=new FormData();data.set("teamSlug",team.slug);data.set("avatar",JSON.stringify(avatar));data.set("kit",JSON.stringify(kit));if(crest)data.set("crest",crest);const r=await fetch("/api/identity",{method:"POST",body:data});const body=await r.json().catch(()=>({}));setBusy(false);setMessage(r.ok?"Identità del club salvata.":body.error??"Salvataggio non riuscito.");if(r.ok&&body.crestUrl)setCrestUrl(`${body.crestUrl}&v=${Date.now()}`);}
 return <><section className="page-heading identity-heading"><div><p className="eyebrow">Club identity studio</p><h1>Il volto del tuo club</h1><p>Crea l’allenatore, disegna la divisa e applica lo stemma della squadra. Potrai modificarli finché la lega non confermerà la divisa ufficiale.</p></div><img src="/bdc-league-crest.png" alt="Stemma della lega"/></section>
 <section className="identity-grid"><article className="surface creator"><div className="surface-title"><div><p className="eyebrow">Allenatore</p><h2>Avatar personale</h2></div></div><div className="avatar-preview" style={{"--skin":avatar.skin,"--eye":avatar.eyeColor,"--hair":avatar.hairColor,"--shirt":avatar.shirt} as React.CSSProperties}><div className={`hair ${avatar.hair}`}/><div className={`face ${avatar.face}`}><div className={`eyes ${avatar.eyes}`}><i/><i/></div><div className="nose"/><div className="mouth"/><div className={`beard ${avatar.beard}`}/></div><div className="avatar-body"/></div><div className="control-grid"><Select label="Forma viso" value={avatar.face} onChange={v=>av("face",v)} items={[["oval","Ovale"],["round","Rotondo"],["square","Squadrato"]]}/><Color label="Carnagione" value={avatar.skin} onChange={v=>av("skin",v)}/><Select label="Occhi" value={avatar.eyes} onChange={v=>av("eyes",v)} items={[["round","Tondi"],["sharp","Affilati"],["soft","Morbidi"]]}/><Color label="Colore occhi" value={avatar.eyeColor} onChange={v=>av("eyeColor",v)}/><Select label="Capelli" value={avatar.hair} onChange={v=>av("hair",v)} items={[["short","Corti"],["wave","Mossi"],["mohawk","Cresta"],["bald","Rasato"]]}/><Color label="Colore capelli" value={avatar.hairColor} onChange={v=>av("hairColor",v)}/><Select label="Barba" value={avatar.beard} onChange={v=>av("beard",v)} items={[["none","Nessuna"],["short","Corta"],["full","Completa"],["goatee","Pizzetto"]]}/><Color label="Colore barba" value={avatar.beardColor} onChange={v=>av("beardColor",v)}/></div></article>
 <article className="surface creator"><div className="surface-title"><div><p className="eyebrow">Match kit</p><h2>Divisa ufficiale</h2></div></div><div className={`jersey-preview pattern-${kit.pattern} collar-${kit.collar}`} style={{"--primary":kit.primary,"--secondary":kit.secondary,"--accent":kit.accent} as React.CSSProperties}><div className="jersey-body"><div className="kit-crest">{crestUrl?<img src={crestUrl} alt="Stemma squadra"/>:<span>{team.name.split(" ").map(x=>x[0]).join("").slice(0,3)}</span>}</div><b>{team.name}</b></div><div className="jersey-shorts" style={{background:kit.shorts}}/></div><div className="control-grid"><Color label="Colore principale" value={kit.primary} onChange={v=>kt("primary",v)}/><Color label="Secondario" value={kit.secondary} onChange={v=>kt("secondary",v)}/><Color label="Dettagli" value={kit.accent} onChange={v=>kt("accent",v)}/><Color label="Pantaloncini" value={kit.shorts} onChange={v=>kt("shorts",v)}/><Select label="Pattern" value={kit.pattern} onChange={v=>kt("pattern",v)} items={[["solid","Tinta unita"],["stripes","Strisce verticali"],["hoops","Fasce orizzontali"],["diagonal","Banda diagonale"],["halves","Due metà"]]}/><Select label="Colletto" value={kit.collar} onChange={v=>kt("collar",v)} items={[["v","A V"],["round","Tondo"],["polo","Polo"]]}/></div><label className="crest-upload"><span><b>Stemma della squadra</b><small>PNG, JPG o WEBP · massimo 2 MB</small></span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseFile(e.target.files?.[0]??null)}/></label></article></section><button className="save-button identity-save" onClick={save} disabled={busy}>{busy?"Salvataggio…":"Salva avatar, divisa e stemma"}</button>{message&&<p className="form-message identity-message">{message}</p>}</>;
}
