"use client";
import { useEffect, useState } from "react";
import type { Team } from "../data/league";
import * as XLSX from "xlsx";

type BalanceRow={teamSlug:string;balance:number};
export function LeagueAdminTools({teams}:{teams:Team[]}){
  const[balances,setBalances]=useState<Record<string,number>>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  function refresh(){fetch("/api/club-finances",{cache:"no-store"}).then(r=>r.json()).then(data=>setBalances(Object.fromEntries((data.balances??[]).map((row:BalanceRow)=>[row.teamSlug,row.balance]))))}
  useEffect(refresh,[]);
  async function saveBalance(teamSlug:string){setBusy(`balance-${teamSlug}`);const response=await fetch("/api/club-finances",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug,balance:balances[teamSlug]})}),data=await response.json().catch(()=>({}));setBusy("");setMessage(response.ok?"Saldo del club aggiornato in tutte le sezioni.":data.error??"Aggiornamento non riuscito.");if(response.ok)refresh()}
  async function importFile(file:File|null){if(!file)return;setBusy("import");setMessage("Lettura e controllo del file…");try{const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]],raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});const rows=raw.filter(row=>String(row.FantaSquadra??"").trim()).map((row,index)=>({teamName:String(row.FantaSquadra).trim(),name:String(row.Nome).trim(),club:String(row["Sq."]).trim(),role:String(row["R.MANTRA"]).trim(),age:Number(row.Under)||0,cost:Number(row.Costo)||0,quotation:Number(row["QUOT."])||0,fvm:Number(row["FVM/1000"])||0,fuoriLista:String(row["Fuori lista"]??"")||null,rowOrder:index}));const response=await fetch("/api/admin/import-rosters",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileName:file.name,rows})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error??"Importazione non riuscita");setMessage(`Importazione completata: ${data.players} calciatori in ${data.teams} club. Le rose precedenti sono state sostituite.`);refresh()}catch(error){setMessage(error instanceof Error?error.message:"File non valido")}finally{setBusy("")}}
  return <section className="surface league-admin-tools"><div><p className="eyebrow">Dati della lega</p><h2>Rose e crediti</h2><p>Importa il file Excel completo oppure correggi il saldo attuale di un club.</p></div><label className="roster-import"><input type="file" accept=".xlsx,.xls" disabled={busy==="import"} onChange={event=>importFile(event.target.files?.[0]??null)}/><b>{busy==="import"?"Importazione in corso…":"Importa e sostituisci tutte le rose"}</b><small>Il file deve contenere tutte le squadre e le colonne FantaSquadra, Nome, Sq., R.MANTRA, Costo, QUOT. e FVM/1000.</small></label><div className="admin-balance-grid">{teams.map(team=><article key={team.slug}><span>{team.name}</span><label><input type="number" value={balances[team.slug]??team.remaining} onChange={event=>setBalances(value=>({...value,[team.slug]:Number(event.target.value)}))}/><em>cr</em></label><button disabled={busy===`balance-${team.slug}`} onClick={()=>saveBalance(team.slug)}>Salva saldo</button></article>)}</div>{message&&<p className="admin-message">{message}</p>}</section>
}
