"use client";
import { useEffect,useState } from "react";
import "../solo.css";
import "../ranking.css";
type Question={prompt:string;clues:string[];options:string[];answer:number};
type Game="guess"|"eleven"|"career"|"survival";
type OfflineRow={team_slug:string;teamName:string;total_points:number;best_score:number;sessions:number};
const games:{id:Game;icon:string;title:string;copy:string}[]=[
 {id:"guess",icon:"◎",title:"Indovina il calciatore",copy:"12 domande · quattro giocatori dello stesso ruolo."},
 {id:"eleven",icon:"◷",title:"Storia della Serie A",copy:"12 domande · squadre, stagioni e imprese storiche."},
 {id:"career",icon:"↗",title:"Carriera del calciatore",copy:"12 carriere · segui le tappe e trova il protagonista."},
 {id:"survival",icon:"♥",title:"Sopravvivenza",copy:"12 domande, tre vite e difficoltà senza pietà."}
];
export function SoloArena(){
 const[game,setGame]=useState<Game|null>(null),[questions,setQuestions]=useState<Question[]>([]),[index,setIndex]=useState(0),[score,setScore]=useState(0),[lives,setLives]=useState(3),[revealed,setRevealed]=useState(0),[feedback,setFeedback]=useState(""),[loading,setLoading]=useState(false),[ranking,setRanking]=useState<OfflineRow[]>([]),[myTeam,setMyTeam]=useState("");
 const question=questions[index],finished=Boolean(game&&questions.length&&(index>=questions.length||lives<=0));
 useEffect(()=>{fetch("/api/arena/solo").then(r=>r.json()).then(data=>{setRanking(data.leaderboard??[]);setMyTeam(data.myTeam??"")}).catch(()=>{})},[]);
 async function start(id:Game){setLoading(true);setFeedback("");const data=await fetch(`/api/arena/solo?game=${id}`).then(r=>r.json());setGame(id);setQuestions(data.questions??[]);setRanking(data.leaderboard??ranking);setMyTeam(data.myTeam??myTeam);setIndex(0);setScore(0);setLives(3);setRevealed(0);setLoading(false)}
 async function saveResult(id:Game,finalScore:number){const data=await fetch("/api/arena/solo",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({game:id,score:finalScore})}).then(r=>r.json()).catch(()=>({}));if(data.leaderboard)setRanking(data.leaderboard)}
 function answer(choice:number){if(!question||feedback||!game)return;const correct=choice===question.answer,points=game==="guess"?Math.max(1,4-revealed):1,finalScore=score+(correct?points:0),nextLives=lives-(game==="survival"&&!correct?1:0);if(correct){setScore(finalScore);setFeedback(`Giusta! +${points} ${points===1?"punto":"punti"}.`)}else{if(game==="survival")setLives(nextLives);setFeedback(`Nope. Era ${question.options[question.answer]}.`)}setTimeout(()=>{const next=index+1;if(nextLives<=0||next>=questions.length){void saveResult(game,finalScore);setIndex(questions.length)}else{setIndex(next);setRevealed(0);setFeedback("")}},900)}
 const offlineRanking=<section className="surface arena-ranking offline-ranking"><div className="surface-title"><div><p className="eyebrow">Punti delle sessioni in solitaria</p><h2><span className="section-icon" aria-hidden="true">★</span>Classifica Offline</h2></div></div><div className="arena-table-wrap"><table><thead><tr><th>#</th><th>Club</th><th>Sessioni</th><th>Record</th><th>Punti</th></tr></thead><tbody>{ranking.length?ranking.map((row,i)=><tr className={row.team_slug===myTeam?"mine":""} key={row.team_slug}><td>{i+1}</td><td><b>{row.teamName}</b></td><td>{row.sessions}</td><td>{row.best_score}</td><td><strong>{row.total_points}</strong></td></tr>):<tr><td colSpan={5}>Nessun punteggio ancora. Qualcuno rompa il ghiaccio.</td></tr>}</tbody></table></div></section>;
 if(!game)return <><section className="surface solo-arena"><div className="surface-title"><div><p className="eyebrow">Modalità giocatore singolo</p><h2>Gioca anche quando gli altri dormono</h2></div><span className="status-dot">12 domande</span></div><div className="solo-game-grid">{games.map(item=><button disabled={loading} key={item.id} onClick={()=>start(item.id)}><span className="game-icon" aria-hidden="true">{item.icon}</span><b>{item.title}</b><small>{item.copy}</small></button>)}</div></section>{offlineRanking}</>;
 if(finished)return <><section className="surface solo-finish"><p className="eyebrow">Sessione completata</p><h2>{score} punti</h2><p>Il risultato è stato aggiunto alla Classifica Offline.</p><div><button className="save-button" onClick={()=>start(game)}>Rigioca</button><button className="secondary-button" onClick={()=>setGame(null)}>Cambia gioco</button></div></section>{offlineRanking}</>;
 return <section className="surface solo-play"><div className="solo-top"><button onClick={()=>setGame(null)}>← Esci</button><b>{games.find(item=>item.id===game)?.title}</b><span>{game==="survival"?`♥ ${lives} · `:""}{index+1}/12 · {score} pt</span></div><div className="solo-progress"><i style={{width:`${((index+1)/12)*100}%`}}/></div><div className="arena-question"><p>{question?.prompt}</p>{question?.clues.length?<div className="arena-clues">{question.clues.slice(0,game==="guess"?revealed:question.clues.length).map((clue,i)=><span key={`${clue}-${i}`}>{clue}</span>)}</div>:null}{game==="guess"&&revealed<question.clues.length?<div className="clue-control"><small>Risposta corretta: {Math.max(1,4-revealed)} punti</small><button className="reveal-button" onClick={()=>setRevealed(value=>value+1)}>Mostra un indizio</button></div>:null}<div className="arena-options">{question?.options.map((option,i)=><button disabled={Boolean(feedback)} onClick={()=>answer(i)} key={`${option}-${i}`}>{option}</button>)}</div>{feedback&&<strong className="solo-feedback">{feedback}</strong>}</div></section>
}
