"use client";
import { useState } from "react";
import "../solo.css";
type Question={prompt:string;clues:string[];options:string[];answer:number};type Game="guess"|"eleven"|"career"|"survival";
const games:{id:Game;number:string;title:string;copy:string}[]=[{id:"guess",number:"01",title:"Indovina il calciatore",copy:"Quattro giocatori dello stesso ruolo: meno indizi usi, più punti fai."},{id:"eleven",number:"02",title:"Storia della Serie A",copy:"Domande secche su squadre, stagioni e imprese storiche."},{id:"career",number:"07",title:"Carriera del calciatore",copy:"Segui le tappe e trova il protagonista."},{id:"survival",number:"10",title:"Sopravvivenza",copy:"Tre vite, 250 domande e difficoltà senza pietà."}];
export function SoloArena(){const[game,setGame]=useState<Game|null>(null),[questions,setQuestions]=useState<Question[]>([]),[index,setIndex]=useState(0),[score,setScore]=useState(0),[lives,setLives]=useState(3),[revealed,setRevealed]=useState(1),[feedback,setFeedback]=useState(""),[loading,setLoading]=useState(false),[best,setBest]=useState<Record<string,number>>({});const question=questions[index],finished=Boolean(game&&questions.length&&(index>=questions.length||lives<=0));
 async function start(id:Game){setLoading(true);setFeedback("");const data=await fetch(`/api/arena/solo?game=${id}`).then(r=>r.json());setGame(id);setQuestions(data.questions??[]);setIndex(0);setScore(0);setLives(3);setRevealed(1);setLoading(false)}
 function answer(choice:number){if(!question||feedback)return;const correct=choice===question.answer,points=game==="guess"?Math.max(1,6-revealed):1;if(correct){setScore(value=>value+points);setFeedback(`Giusta! +${points} ${points===1?"punto":"punti"}.`)}else{if(game==="survival")setLives(value=>value-1);setFeedback(`Nope. Era ${question.options[question.answer]}.`)}setTimeout(()=>{const next=index+1;if((game==="survival"&&lives-(correct?0:1)<=0)||next>=questions.length){const finalScore=score+(correct?points:0);setBest(current=>({...current,[game!]:Math.max(current[game!]??0,finalScore)}));setIndex(questions.length)}else{setIndex(next);setRevealed(1);setFeedback("")}},900)}
 if(!game)return <section className="surface solo-arena"><div className="surface-title"><div><p className="eyebrow">Modalità giocatore singolo</p><h2>Gioca anche quando gli altri dormono</h2></div><span className="status-dot">4 modalità</span></div><div className="solo-game-grid">{games.map(item=><button disabled={loading} key={item.id} onClick={()=>start(item.id)}><span>{item.number}</span><b>{item.title}</b><small>{item.copy}</small></button>)}</div></section>;
 if(finished)return <section className="surface solo-finish"><p className="eyebrow">Partita terminata</p><h2>{score} punti</h2><p>Record modalità: <b>{Math.max(best[game]??0,score)}</b></p><div><button className="save-button" onClick={()=>start(game)}>Rigioca</button><button className="secondary-button" onClick={()=>setGame(null)}>Cambia gioco</button></div></section>;
 return <section className="surface solo-play"><div className="solo-top"><button onClick={()=>setGame(null)}>← Esci</button><b>{games.find(item=>item.id===game)?.title}</b><span>{game==="survival"?`❤ ${lives}`:`${index+1}/${questions.length}`} · {score} pt</span></div><div className="solo-progress"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div><div className="arena-question"><p>{question?.prompt}</p>{question?.clues.length?<div className="arena-clues">{question.clues.slice(0,game==="guess"?revealed:question.clues.length).map((clue,i)=><span key={`${clue}-${i}`}>{clue}</span>)}</div>:null}{game==="guess"&&revealed<question.clues.length?<button className="reveal-button" onClick={()=>setRevealed(value=>value+1)}>Altro indizio −1 punto</button>:null}<div className="arena-options">{question?.options.map((option,i)=><button disabled={Boolean(feedback)} onClick={()=>answer(i)} key={`${option}-${i}`}>{option}</button>)}</div>{feedback&&<strong className="solo-feedback">{feedback}</strong>}</div></section>}
