"use client";

import { useEffect, useMemo, useState } from "react";
import type { Team } from "../data/league";

type ChoiceKey = "sportingDirector" | "stadium" | "medicalCenter" | "youthAcademy" | "trainingCenter";
const options: { key: ChoiceKey; title: string; description: string; cost: number }[] = [
  { key: "sportingDirector", title: "Direttore Sportivo", description: "Secondo Under 21 riconfermabile", cost: 25 },
  { key: "stadium", title: "Stadio", description: "Bonus +0,5 nelle gare casalinghe", cost: 30 },
  { key: "medicalCenter", title: "Centro medico", description: "Un intervento emergenziale per infortunio lungo", cost: 15 },
  { key: "youthAcademy", title: "Settore giovanile", description: "Stipendio dimezzato per un calciatore Primavera", cost: 20 },
  { key: "trainingCenter", title: "Centro allenamento", description: "Sconto sulla riconferma di un calciatore Over", cost: 20 },
];
const emptyChoices: Record<ChoiceKey, boolean> = { sportingDirector: false, stadium: false, medicalCenter: false, youthAcademy: false, trainingCenter: false };

export function TeamDashboard({ team, canEdit }: { team: Team; canEdit: boolean }) {
  const [choices, setChoices] = useState(emptyChoices), [saved, setSaved] = useState<string | null>(null), [lockedAt, setLockedAt] = useState<string | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { fetch(`/api/choices?team=${team.slug}`).then(r => r.json()).then(data => { if(data.choice){ setChoices({sportingDirector:Boolean(data.choice.sporting_director),stadium:Boolean(data.choice.stadium),medicalCenter:Boolean(data.choice.medical_center),youthAcademy:Boolean(data.choice.youth_academy),trainingCenter:Boolean(data.choice.training_center)}); setSaved(data.choice.updated_at); setLockedAt(data.choice.locked_at); }}).catch(() => {}); }, [team.slug]);
  const selectedCount = Object.values(choices).filter(Boolean).length;
  const salary = Math.ceil(team.spent * .08), carry = Math.min(team.remaining, 50), structures = options.reduce((sum, option) => sum + (choices[option.key] ? option.cost : 0), 0), projected = 500 + carry - salary - structures;
  const roleCounts = useMemo(() => team.roster.reduce<Record<string, number>>((acc, p) => { const key = p.role === "Por" ? "Portieri" : /Dc|Dd|Ds|B/.test(p.role) ? "Difensori" : /Pc/.test(p.role) || p.role === "A" ? "Attaccanti" : "Centrocampisti"; acc[key] = (acc[key] ?? 0) + 1; return acc; }, {}), [team]);
  function toggle(key: ChoiceKey, value: boolean){if(value && selectedCount >= 2)return;setChoices(previous=>({...previous,[key]:value}));setMessage("");}
  async function save(){if(selectedCount!==2){setMessage("Devi scegliere esattamente 2 opzioni.");return;}setBusy(true);const response=await fetch("/api/choices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"societal",teamSlug:team.slug,...choices})});const data=await response.json().catch(()=>({}));setBusy(false);if(response.ok){setSaved(data.updatedAt);setLockedAt(data.lockedAt);setMessage("Scelte pubblicate e bloccate fino alla prossima stagione.");}else setMessage(data.error??"Salvataggio non riuscito.");}
  const editable = canEdit && !lockedAt;
  return <>
    <section className="club-hero"><div><p className="eyebrow">La mia società</p><h1>{team.name}</h1><p>La tua scrivania per pianificare la prossima stagione, gestire la rosa e pubblicare le decisioni societarie.</p><div className="hero-actions"><a className="primary-link" href="/formazione">Schiera la formazione</a><a className="secondary-link" href={`/club/${team.slug}`}>Apri rosa completa</a></div></div><div className="club-monogram">{team.name.split(" ").map(x=>x[0]).join("").slice(0,3)}</div></section>
    <section className="kpi-row"><article><span>Crediti residui</span><strong>{team.remaining}</strong><small>situazione attuale</small></article><article><span>Costo rosa</span><strong>{team.spent}</strong><small>su 500 iniziali</small></article><article><span>Stipendi stimati</span><strong>{salary}</strong><small>aliquota 8%</small></article><article><span>Under 21</span><strong>{team.under21}</strong><small>in rosa</small></article></section>
    <section className="dashboard-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Pianificazione 2027/28</p><h2>Scelte societarie <small className="choice-counter">{selectedCount}/2</small></h2></div><span className="status-dot">{lockedAt ? "Bloccate" : saved ? "Pubblicate" : "Da salvare"}</span></div>{lockedAt&&<div className="lock-notice"><b>Scelte definitive</b><span>Solo l’amministratore può riaprire le modifiche prima della prossima stagione.</span></div>}<div className="choice-list">{options.map(option=><label className={`choice-row ${choices[option.key]?"selected":""}`} key={option.key}><span><b>{option.title}</b><small>{option.description}</small></span><em>{option.cost} cr</em><input type="checkbox" checked={choices[option.key]} disabled={!editable||(!choices[option.key]&&selectedCount>=2)} onChange={e=>toggle(option.key,e.target.checked)} /></label>)}</div>{editable&&<button className="save-button" onClick={save} disabled={busy||selectedCount!==2}>{busy ? "Salvataggio…" : "Conferma 2 scelte e bloccale"}</button>}{message&&<p className="form-message">{message}</p>}</div>
      <div className="budget-surface"><p>Budget previsto prima delle riconferme</p><strong>{projected}</strong><span>crediti</span><dl><div><dt>Base</dt><dd>500</dd></div><div><dt>Riporto</dt><dd className="positive">+{carry}</dd></div><div><dt>Stipendi</dt><dd>−{salary}</dd></div><div><dt>Strutture</dt><dd>−{structures}</dd></div></dl></div></section>
    <section className="dashboard-grid lower"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Composizione</p><h2>Rosa attuale</h2></div><a href={`/club/${team.slug}`}>Vedi tutti</a></div><div className="role-grid">{Object.entries(roleCounts).map(([role,count])=><div key={role}><span>{role}</span><strong>{count}</strong></div>)}</div><div className="mini-roster">{team.roster.slice(0,5).map(player=><div key={player.name}><span>{player.role}</span><b>{player.name}</b><em>{player.cost} cr</em></div>)}</div></div><div className="surface"><p className="eyebrow">Riconferme potenziali</p><h2>Talenti da proteggere</h2><div className="prospects">{team.roster.filter(p=>p.age<=21).slice(0,5).map(p=><div key={p.name}><span>{p.age} anni</span><b>{p.name}</b><em>{p.role} · {p.cost} cr</em></div>)}</div></div></section>
  </>;
}
