"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { Team } from "../data/league";

export function TeamDashboard({ team, canEdit }: { team: Team; canEdit: boolean }) {
  const [director, setDirector] = useState(false), [stadium, setStadium] = useState(false), [saved, setSaved] = useState<string | null>(null), [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/choices?team=${team.slug}`).then(r => r.json()).then(data => { if(data.choice){ setDirector(Boolean(data.choice.sporting_director)); setStadium(Boolean(data.choice.stadium)); setSaved(data.choice.updated_at); }}).catch(() => {}); }, [team.slug]);
  const salary = Math.ceil(team.spent * .08), carry = Math.min(team.remaining, 50), structures = (director ? 25 : 0) + (stadium ? 30 : 0), projected = 500 + carry - salary - structures;
  const roleCounts = useMemo(() => team.roster.reduce<Record<string, number>>((acc, p) => { const key = p.role === "Por" ? "Portieri" : /Dc|Dd|Ds|B/.test(p.role) ? "Difensori" : /Pc/.test(p.role) || p.role === "A" ? "Attaccanti" : "Centrocampisti"; acc[key] = (acc[key] ?? 0) + 1; return acc; }, {}), [team]);
  async function save(){setBusy(true);const response=await fetch("/api/choices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({teamSlug:team.slug,sportingDirector:director,stadium})});setBusy(false);if(response.ok)setSaved(new Date().toISOString());}
  return <>
    <section className="club-hero"><div><p className="eyebrow">La mia società</p><h1>{team.name}</h1><p>La tua scrivania per pianificare la prossima stagione, gestire la rosa e pubblicare le decisioni societarie.</p><div className="hero-actions"><Link className="primary-link" href="/formazione">Schiera la formazione</Link><Link className="secondary-link" href={`/club/${team.slug}`}>Apri rosa completa</Link></div></div><div className="club-monogram">{team.name.split(" ").map(x=>x[0]).join("").slice(0,3)}</div></section>
    <section className="kpi-row"><article><span>Crediti residui</span><strong>{team.remaining}</strong><small>situazione attuale</small></article><article><span>Costo rosa</span><strong>{team.spent}</strong><small>su 500 iniziali</small></article><article><span>Stipendi stimati</span><strong>{salary}</strong><small>aliquota 8%</small></article><article><span>Under 21</span><strong>{team.under21}</strong><small>in rosa</small></article></section>
    <section className="dashboard-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Pianificazione 2027/28</p><h2>Scelte societarie</h2></div><span className="status-dot">{saved ? "Pubblicate" : "Da salvare"}</span></div><label className="choice-row"><span><b>Direttore Sportivo</b><small>Secondo Under 21 riconfermabile</small></span><em>25 cr</em><input type="checkbox" checked={director} disabled={!canEdit} onChange={e=>setDirector(e.target.checked)} /></label><label className="choice-row"><span><b>Stadio</b><small>Bonus +0,5 nelle gare casalinghe</small></span><em>30 cr</em><input type="checkbox" checked={stadium} disabled={!canEdit} onChange={e=>setStadium(e.target.checked)} /></label>{canEdit && <button className="save-button" onClick={save} disabled={busy}>{busy ? "Salvataggio…" : "Salva e pubblica le scelte"}</button>}</div>
      <div className="budget-surface"><p>Budget previsto prima delle riconferme</p><strong>{projected}</strong><span>crediti</span><dl><div><dt>Base</dt><dd>500</dd></div><div><dt>Riporto</dt><dd className="positive">+{carry}</dd></div><div><dt>Stipendi</dt><dd>−{salary}</dd></div><div><dt>Strutture</dt><dd>−{structures}</dd></div></dl></div></section>
    <section className="dashboard-grid lower"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Composizione</p><h2>Rosa attuale</h2></div><Link href={`/club/${team.slug}`}>Vedi tutti</Link></div><div className="role-grid">{Object.entries(roleCounts).map(([role,count])=><div key={role}><span>{role}</span><strong>{count}</strong></div>)}</div><div className="mini-roster">{team.roster.slice(0,5).map(player=><div key={player.name}><span>{player.role}</span><b>{player.name}</b><em>{player.cost} cr</em></div>)}</div></div><div className="surface"><p className="eyebrow">Riconferme potenziali</p><h2>Talenti da proteggere</h2><div className="prospects">{team.roster.filter(p=>p.age<=21).slice(0,5).map(p=><div key={p.name}><span>{p.age} anni</span><b>{p.name}</b><em>{p.role} · {p.cost} cr</em></div>)}</div></div></section>
  </>;
}
