"use client";
import { useEffect,useMemo,useState } from "react";
import type { Team } from "../data/league";
import { ClubCrest } from "./ClubCrest";

type ChoiceKey="sportingDirector"|"stadium"|"prestanome"|"youthAcademy"|"trainingCenter";
type SalaryPayment={tranche:number;amount:number;charged_at:string};
const options:{key:ChoiceKey;title:string;description:string;cost:number}[]=[
  {key:"sportingDirector",title:"Direttore Sportivo",description:"Secondo Under 21 riconfermabile",cost:25},
  {key:"stadium",title:"Stadio",description:"Bonus +0,5 nelle gare casalinghe",cost:30},
  {key:"prestanome",title:"Prestanome",description:"Abilita l’accesso al Centro scommesse",cost:10},
  {key:"youthAcademy",title:"Settore giovanile",description:"Stipendio dimezzato per un calciatore Primavera",cost:20},
  {key:"trainingCenter",title:"Centro allenamento",description:"Sconto sulla riconferma di un calciatore Over",cost:35},
];
const emptyChoices:Record<ChoiceKey,boolean>={sportingDirector:false,stadium:false,prestanome:false,youthAcademy:false,trainingCenter:false};

export function TeamDashboard({team,canEdit}:{team:Team;canEdit:boolean}){
  const[choices,setChoices]=useState(emptyChoices),[saved,setSaved]=useState<string|null>(null),[lockedAt,setLockedAt]=useState<string|null>(null),[salaryPayments,setSalaryPayments]=useState<SalaryPayment[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetch(`/api/choices?team=${team.slug}`).then(r=>r.json()).then(data=>{if(data.choice){setChoices({sportingDirector:Boolean(data.choice.sporting_director),stadium:Boolean(data.choice.stadium),prestanome:Boolean(data.choice.medical_center),youthAcademy:Boolean(data.choice.youth_academy),trainingCenter:Boolean(data.choice.training_center)});setSaved(data.choice.updated_at);setLockedAt(data.choice.locked_at)}}).catch(()=>{})},[team.slug]);
  useEffect(()=>{fetch(`/api/salaries?team=${team.slug}`).then(r=>r.json()).then(data=>setSalaryPayments(data.payments??[])).catch(()=>{})},[team.slug]);
  const selectedCount=Object.values(choices).filter(Boolean).length,salaryInstallment=Math.ceil(team.spent*.03),paidSalary=salaryPayments.reduce((sum,p)=>sum+p.amount,0),currentRemaining=Math.max(0,team.remaining-paidSalary),carry=Math.min(currentRemaining,50),structures=options.reduce((sum,o)=>sum+(choices[o.key]?o.cost:0),0),projected=500+carry-structures;
  const roleCounts=useMemo(()=>team.roster.reduce<Record<string,number>>((acc,p)=>{const key=p.role==="Por"?"Portieri":/Dc|Dd|Ds|B/.test(p.role)?"Difensori":/Pc/.test(p.role)||p.role==="A"?"Attaccanti":"Centrocampisti";acc[key]=(acc[key]??0)+1;return acc},{}),[team]);
  function toggle(key:ChoiceKey,value:boolean){if(value&&selectedCount>=2)return;setChoices(previous=>({...previous,[key]:value}));setMessage("")}
  async function save(){setBusy(true);const response=await fetch("/api/choices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"societal",teamSlug:team.slug,...choices})}),data=await response.json().catch(()=>({}));setBusy(false);if(response.ok){setSaved(data.updatedAt);setLockedAt(data.lockedAt);setMessage("Scelte pubblicate e bloccate fino alla prossima stagione.")}else setMessage(data.error??"Salvataggio non riuscito.")}
  const editable=canEdit&&!lockedAt;
  return <>
    <section className="club-hero"><div><p className="eyebrow">La mia società</p><h1>{team.name}</h1><p>La tua scrivania per pianificare la prossima stagione, gestire la rosa e pubblicare le decisioni societarie.</p><div className="hero-actions"><a className="primary-link" href="/formazione">Schiera la formazione</a><a className="secondary-link" href={`/club/${team.slug}`}>Apri rosa completa</a></div></div><ClubCrest teamSlug={team.slug} teamName={team.name} size="large"/></section>
    <section className="kpi-row"><article><span>Crediti residui</span><strong>{currentRemaining}</strong><small>{paidSalary?`${paidSalary} scalati per stipendi`:"nessuna tranche scalata"}</small></article><article><span>Costo rosa</span><strong>{team.spent}</strong><small>su 500 iniziali</small></article><article><span>Prossima tranche</span><strong>{salaryInstallment}</strong><small>3% sul valore attuale</small></article><article><span>Tranche pagate</span><strong>{salaryPayments.length}/2</strong><small>stagione corrente</small></article></section>
    <section className="dashboard-grid"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Pianificazione 2027/28</p><h2>Scelte societarie <small className="choice-counter">{selectedCount}/2 max</small></h2></div><span className="status-dot">{lockedAt?"Bloccate":saved?"Pubblicate":"Da salvare"}</span></div>{lockedAt&&<div className="lock-notice"><b>Scelte definitive</b><span>Solo l’amministratore può riaprire le modifiche prima della prossima stagione.</span></div>}<div className="choice-list">{options.map(option=><label className={`choice-row ${choices[option.key]?"selected":""}`} key={option.key}><span><b>{option.title}</b><small>{option.description}</small></span><em>{option.cost} cr</em><input type="checkbox" checked={choices[option.key]} disabled={!editable||(!choices[option.key]&&selectedCount>=2)} onChange={e=>toggle(option.key,e.target.checked)}/></label>)}</div>{editable&&<button className="save-button" onClick={save} disabled={busy}>{busy?"Salvataggio…":selectedCount?`Conferma ${selectedCount} scelt${selectedCount===1?"a":"e"} e blocca`:"Conferma nessuna scelta e blocca"}</button>}{message&&<p className="form-message">{message}</p>}</div>
      <div className="budget-surface"><p>Budget previsto prima delle riconferme</p><strong>{projected}</strong><span>crediti</span><div className="salary-schedule"><p className="eyebrow">Stipendi stagione corrente</p>{[1,2].map(tranche=>{const paid=salaryPayments.find(p=>p.tranche===tranche);return <div key={tranche}><span>{tranche===1?"Prima":"Seconda"} tranche · 3% {paid&&<small>Pagata il {new Date(paid.charged_at).toLocaleDateString("it-IT")}</small>}</span><b>{paid?`−${paid.amount}`:`Previsti −${salaryInstallment}`}</b></div>})}<small>La cifra viene fissata e scalata soltanto quando l’amministratore conferma la tranche.</small></div><dl><div><dt>Base prossima stagione</dt><dd>500</dd></div><div><dt>Riporto attuale</dt><dd className="positive">+{carry}</dd></div><div><dt>Scelte societarie</dt><dd>−{structures}</dd></div></dl></div></section>
    <section className="dashboard-grid lower"><div className="surface"><div className="surface-title"><div><p className="eyebrow">Composizione</p><h2>Rosa attuale</h2></div><a href={`/club/${team.slug}`}>Vedi tutti</a></div><div className="role-grid">{Object.entries(roleCounts).map(([role,count])=><div key={role}><span>{role}</span><strong>{count}</strong></div>)}</div><div className="mini-roster">{team.roster.slice(0,5).map(player=><div key={player.name}><span>{player.role}</span><b>{player.name}</b><em>{player.cost} cr</em></div>)}</div></div><div className="surface"><p className="eyebrow">Riconferme potenziali</p><h2>Talenti da proteggere</h2><div className="prospects">{team.roster.filter(p=>p.age<=21).slice(0,5).map(p=><div key={p.name}><span>{p.age} anni</span><b>{p.name}</b><em>{p.role} · {p.cost} cr</em></div>)}</div></div></section>
  </>
}
