import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { getTeam,teams } from "../../../data/league";
import { serieAHistoricalQuiz } from "../../../data/serieAQuiz";
import { careerCards,mysteryElevens } from "../../../data/soloArena";
import { teamForEmail } from "../../../lib/identity";

type SoloQuestion={prompt:string;clues:string[];options:string[];answer:number};
type ScoreRow={team_slug:string;total_points:number;best_score:number;sessions:number};
const shuffle=<T,>(items:T[])=>[...items].sort(()=>Math.random()-.5);
const players=()=>teams.flatMap(team=>team.roster).filter((player,index,list)=>list.findIndex(item=>item.name===player.name)===index);
function options(correct:string,pool:string[]){return shuffle([correct,...shuffle([...new Set(pool)].filter(item=>item!==correct)).slice(0,3)])}
function playerQuestions(){const pool=players();return shuffle(pool).flatMap(player=>{const sameRole=pool.filter(item=>item.role===player.role);if(sameRole.length<4)return[];const names=options(player.name,sameRole.map(item=>item.name)),clubs=options(player.club,pool.map(item=>item.club)),roles=options(player.role,pool.map(item=>item.role));return[{prompt:"Chi è il calciatore?",clues:[`Ruolo Mantra: ${player.role}`,`Età: ${player.age}`,`Club: ${player.club}`,`Quotazione: ${player.quotation}`,`FVM: ${player.fvm}`],options:names,answer:names.indexOf(player.name)},{prompt:`In quale club gioca ${player.name}?`,clues:[`Ruolo: ${player.role}`,`Età: ${player.age}`],options:clubs,answer:clubs.indexOf(player.club)},{prompt:`Qual è il ruolo Mantra di ${player.name}?`,clues:[`Club: ${player.club}`,`Età: ${player.age}`],options:roles,answer:roles.indexOf(player.role)}]})}
function careerQuestions(){return shuffle(careerCards).map(card=>{const names=options(card.player,careerCards.map(item=>item.player));return{prompt:"Di quale calciatore è questa carriera?",clues:[card.clubs.join("  →  "),`Nazionalità: ${card.nationality}`,`Ruolo: ${card.role}`],options:names,answer:names.indexOf(card.player)}})}
function historyQuestions(){return shuffle(mysteryElevens).map(card=>{const choices=shuffle(card.options);return{prompt:card.prompt,clues:[],options:choices,answer:choices.indexOf(card.answer)}})}
function generalQuestions(){return shuffle(serieAHistoricalQuiz).map(item=>{const choices=shuffle(item.options);return{prompt:item.prompt,clues:[],options:choices,answer:choices.indexOf(item.correct)}})}
async function ensureScores(){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS arena_solo_scores (team_slug TEXT PRIMARY KEY NOT NULL,total_points INTEGER NOT NULL DEFAULT 0,best_score INTEGER NOT NULL DEFAULT 0,sessions INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_arena_solo_total_points ON arena_solo_scores(total_points DESC)")]);await env.DB.prepare("PRAGMA optimize").run()}
async function actor(){const user=await getChatGPTUser();if(!user)return null;const team=await teamForEmail(user.email);return team?{user,team}:null}
async function leaderboard(){const rows=await env.DB.prepare("SELECT team_slug,total_points,best_score,sessions FROM arena_solo_scores ORDER BY total_points DESC,best_score DESC,sessions ASC LIMIT 12").all<ScoreRow>();return rows.results.map(row=>({...row,teamName:getTeam(row.team_slug)?.name??row.team_slug}))}

export async function GET(request:Request){const current=await actor();if(!current)return Response.json({error:"Accesso richiesto"},{status:401});await ensureScores();const game=new URL(request.url).searchParams.get("game");if(!game)return Response.json({leaderboard:await leaderboard(),myTeam:current.team});let questions:SoloQuestion[]=[];if(game==="guess")questions=playerQuestions().filter(item=>item.prompt==="Chi è il calciatore?");else if(game==="eleven")questions=historyQuestions();else if(game==="career")questions=careerQuestions();else if(game==="survival")questions=shuffle([...playerQuestions(),...careerQuestions(),...historyQuestions(),...generalQuestions()]);else return Response.json({error:"Gioco non valido"},{status:400});questions=shuffle(questions).slice(0,12);return Response.json({game,total:questions.length,questions,leaderboard:await leaderboard(),myTeam:current.team})}

export async function POST(request:Request){const current=await actor();if(!current)return Response.json({error:"Accesso richiesto"},{status:401});await ensureScores();const body=await request.json()as{game?:string;score?:number};const score=Number(body.score),validGame=["guess","eleven","career","survival"].includes(body.game??""),maxScore=body.game==="guess"?48:12;if(!validGame||!Number.isInteger(score)||score<0||score>maxScore)return Response.json({error:"Punteggio non valido"},{status:400});const now=new Date().toISOString();await env.DB.prepare("INSERT INTO arena_solo_scores(team_slug,total_points,best_score,sessions,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(team_slug) DO UPDATE SET total_points=total_points+excluded.total_points,best_score=MAX(best_score,excluded.best_score),sessions=sessions+1,updated_at=excluded.updated_at").bind(current.team,score,score,1,now).run();return Response.json({ok:true,leaderboard:await leaderboard()})}
